sudo: required

language: java
jdk:
 - openjdk8
 
before_install:
  - chmod +x mvnw
  
before_script:
  - curl https://cli-assets.heroku.com/install.sh | sh
  
script: ./mvnw clean install

deploy:  
  provider: script
  skip_cleanup: true
  script:
    heroku deploy:jar -j target/springboot-gth-alpha-0.0.1-SNAPSHOT.jar - i ./Procfile --app
  on: 
    branch: main

    

